const User =[
    {
        "id":1,
        "name":"Jhone",
        "email":"Jhone@gmail.com",
        "role":"Developer"
    },
    {
        "id":2,
        "name":"Smith",
        "email":"Smith@gmail.com",
        "role":"Developer"
    },
    {
        "id":3,
        "name":"Rate",
        "email":"Rate@gmail.com",
        "role":"QA Tester"
    },
    {
        "id":4,
        "name":"Jhone",
        "email":"Jhone@gmail.com",
        "role":"QA Engineer"
    },
    {
        "id":5,
        "name":"Jhone",
        "email":"Jhone@gmail.com",
        "role":"Manager"
    },
    {
        "id":6,
        "name":"Jhone",
        "email":"Jhone@gmail.com",
        "role":"BA"
    },
    {
        "id":7,
        "name":"Jhone",
        "email":"Jhone@gmail.com",
        "role":"BA"
    },
    {
        "id":8,
        "name":"Jhone",
        "email":"Jhone@gmail.com",
        "role":"QA Tester"
    },
    {
        "id":9,
        "name":"Jhone",
        "email":"Jhone@gmail.com",
        "role":"Developer"
    },
    {
        "id":10,
        "name":"Jhone",
        "email":"Jhone@gmail.com",
        "role":"Manager"
    },
    {
        "id":11,
        "name":"Jhone",
        "email":"Jhone@gmail.com",
        "role":"Developer"
    },
    {
        "id":12,
        "name":"Jhone",
        "email":"Jhone@gmail.com",
        "role":"Developer"
    },
    {
        "id":13,
        "name":"Jhone",
        "email":"Jhone@gmail.com",
        "role":"Developer"
    }
]
export default User;